[package]
name = "nfq"
version = "0.2.6"
authors = ["Gary Guo <gary@garyguo.net>"]
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Rust library for dealing with NetFilter queue"
keywords = ["netfilter", "nfqueue", "iptables"]
homepage = "https://github.com/nbdd0121/nfq-rs"
repository = "https://github.com/nbdd0121/nfq-rs.git"

[dependencies]
libc = "0.2"
bytes = "1.5"
bytemuck = { version = "1.14", features = ["derive"] }
tokio = { version = "1.0", features = ["net", "rt", "sync", "time"] }

[features]
ct = []
